{
    'name': 'SNIM Outillage',
    'version': '19.0.1.0.0',
    'license': 'LGPL-3',
    'category': 'Maintenance',
    'summary': 'Gestion des instruments et outillage SNIM',
    'description': 'Module de gestion des instruments de mesure SNIM',
    'author': 'Salma',
    'depends': ['base', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'views/instrument_views.xml',
        'views/fiche_vie_views.xml',
        'views/reforme_views.xml',
        'wizard/import_instrument_wizard_views.xml',
        'views/menu_views.xml',
        'report/fiche_vie_report.xml',
    ],
    'assets': {},
    'installable': True,
    'application': True,
    'auto_install': False,
}