[options]
addons_path = /home/salma/odoo19/addons,/home/salma/odoo19-custom-addons
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo
db_name = odoo19
http_port = 8069
log_level = info
admin_passwd = $pbkdf2-sha512$600000$Zay1lvIew7iXsvYe49zb2w$jnLSAX5C7vI3B1.YQZq61KVcx.tHDsam96jD.ohLyab8BreYRS5UwjPDzBjl6qd71RV4wK89hrVV5La/5BxXtA

